name: First workflow
on:
  - pull_request
  - workflow_dispatch
  - push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: build app
        run: mvn clean install
      - name: Run tests
        run: mvn test
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=va-spec
            -Dsonar.projectKey=DemoActions
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  deploy:
    needs: [tests] # to make it parallel
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "deploying"
